### ISSUE TITLE
Initial Implementation of `RogueLikeMap`'s Terrain does not allow for updating existing terrain

### ISSUE THREAD

**Issue by fcheadle** [thesadrogue/TheSadRogue.Integration#4]
The current implementation in the example game does not allow for edits of terrain after it has been initialized. This is because we are supply the ScreenSurface's initial cells upon creation; we should have a more flexible way of doing this so that we can alter terrain after creation.

**Comment by fcheadle** [comment]
Pulled from PR Comments: 

> This method doesn't support having multiple surfaces that render a single map, since an EntityRenderer can be added to only one surface.

**Comment by Chris3606** [comment]
The issue you mention in the comment is different than the one initially described; the one from the comment has been moved to #16 .

Regarding the edits of terrain, a subclass of `CellSurface` at minimum is necessary, since the set functionality for the indexers of `CellSurface` is `protected`.

However, this issue may go hand-in-hand with #9 , which may require a custom `ICellSurface` to do anyway; so it may be worth solving these in one architecture refactor.

**Comment by Thraka** [comment]
Because of the restructure of SadConsole v9, I don't think we need to do this whole attach-to-surface map object system anymore. `RoguelikeMap` could explicitly implement `IScreenObject`, hiding all of the SadConsole aspects we choose, yet, still be able to directly add the map to the SadConsole object model.

This would enable easier code for the user:

```csharp
Map = GenerateMap();
PlayerCharacter = GeneratePlayerCharacter();
Map.AddEntity(PlayerCharacter);
GameHost.Instance.Screen = MapWindow;
```

And the `RoguelikeMap` could be implemented similar to:

```csharp
partial class RoguelikeMap : Map, IScreenObject
{
    private IScreenObject _screenObjectWrapper;

    // In RoguelikeMap.ScreenObject.cs
    FocusBehavior IScreenObject.FocusedMode { get => _screenObjectWrapper.FocusedMode; set => _screenObjectWrapper.FocusedMode = value; }
    Point IScreenObject.AbsolutePosition => _screenObjectWrapper.AbsolutePosition;
    ScreenObjectCollection IScreenObject.Children => _screenObjectWrapper.Children;
    
.... more props/events/etc
```

With the map having layers (unsure how many, terrain, entity? more?) each can possibly be added as a surface to the map as a child which automatically renders the layer. You would just need to expose a viewport (maybe map has that already) and forward that to each surface.

**Comment by Chris3606** [comment]
@Thraka I agree that's a possible solution, and maybe the one we should pursue as it would allow near-perfect control; but it also feels like duplicating an insane amount of rendering code, which needs to be highly optimized and particularly crafted to work well.

**Comment by Chris3606** [comment]
Actually, I amend my previous statement.  I don't think there's that terribly much duplication of render code since the render steps refactor.

**Comment by Chris3606** [comment]
The other thing to remember is that, at least currently, everything that's not terrain is an Entity so is covered by `Entities.Renderer`.

Even if this were somehow simplified to cell surfaces, another use case to consider is where different viewports of the map are being renderer on the same screen; another reason to consider separating rendering from map data.

@Thraka  If we did implement `IScreenObject` on `Map`, or create some class that did it, it would still involve cell surfaces, correct?  How would we update them and keep them in sync?  I think most of the issues we have revolve around the cell surface interface.

**Comment by Chris3606** [comment]
The proposal for `IScreenObject` has been captured in #22 .  This specific issue is closed, and remaining desync issues are covered in #21 .
