### ISSUE TITLE
Crash with 'TypeLoadException'

### ISSUE THREAD

**Issue by Frednotbob** [thesadrogue/TheSadRogue.Integration#77]
System.TypeLoadException: 'Method 'add_IsEnabledChanged' in type 'SadRogue.Integration.Maps.RogueLikeMap' from assembly 'TheSadRogue.Integration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

When using the integration library (1.0.0Beta04-debug) on top of the current SadConsole example code (from the SadConsole GitHub repository, the project crashes out with the above exception at 'Game.Instance.Run()'

**Comment by Chris3606** [comment]
I believe this is an issue when the integration library is used with the v10 code because the current integration library version does not support v10.

This should be fixed when v1.0.0 is released (which will suppport v10), which should happen in a matter of days; we'll double check  at that time, then close this ticket as needed.

**Comment by Chris3606** [comment]
Closed with #76
